### ISSUE TITLE
noploop script

### ISSUE THREAD

**Issue by ElijahLynn** [brendangregg/pmc-cloud-tools#2]
Is the noploop script that was mentioned here available => http://www.brendangregg.com/blog/2017-05-04/the-pmcs-of-ec2.html

**Comment by koxt** [comment]
@ElijahLynn Brendan used `noploop` in his previous post [http://www.brendangregg.com/blog/2014-04-26/the-noploop-cpu-benchmark.html](http://www.brendangregg.com/blog/2014-04-26/the-noploop-cpu-benchmark.html)

**Comment by ElijahLynn** [comment]
Nice, thank you!
